#ifdef EXTERN_CG_CVAR
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) extern vmCvar_t vmCvar;
#endif

#ifdef DECLARE_CG_CVAR
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) vmCvar_t vmCvar;
#endif

#ifdef CG_CVAR_LIST
	#define CG_CVAR( vmCvar, cvarName, defaultString, cvarFlags ) { & vmCvar, cvarName, defaultString, cvarFlags },
#endif

CG_CVAR( cg_ignore, "cg_ignore", "0", 0 )	// used for debugging
CG_CVAR( cg_displayObituary, "cg_displayObituary", "0", CVAR_ARCHIVE )
CG_CVAR( cg_zoomFov, "cg_zoomfov", "22.5", CVAR_ARCHIVE )
CG_CVAR( cg_fov, "cg_fov", "90", CVAR_ARCHIVE )
CG_CVAR( cg_viewsize, "cg_viewsize", "100", CVAR_ARCHIVE )
CG_CVAR( cg_shadows, "cg_shadows", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_gibs, "cg_gibs", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_scripted2D, "cg_scripted2D", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_scriptedCamera, "cg_scriptedCamera", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_draw2D, "cg_draw2D", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_drawStatus, "cg_drawStatus", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_drawTimer, "cg_drawTimer", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_drawFPS, "cg_drawFPS", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_drawFrameTime, "cg_drawFrameTime", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_drawSnapshot, "cg_drawSnapshot", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_draw3dIcons, "cg_draw3dIcons", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_advancedFlight, "cg_advancedFlight", "0", CVAR_USERINFO |CVAR_ARCHIVE  )
CG_CVAR( cg_drawIcons, "cg_drawIcons", "1", CVAR_ARCHIVE  )
CG_CVAR( cg_drawCrosshair, "cg_drawCrosshair", "4", CVAR_ARCHIVE )
CG_CVAR( cg_drawCrosshairNames, "cg_drawCrosshairNames", "1", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairSize, "cg_crosshairSize", "3", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairMargin, "cg_crosshairMargin", "4", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairBars, "cg_crosshairBars", "0", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairHealth, "cg_crosshairHealth", "1", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairX, "cg_crosshairX", "0", CVAR_ARCHIVE )
CG_CVAR( cg_crosshairY, "cg_crosshairY", "0", CVAR_ARCHIVE )
CG_CVAR( cg_brassTime, "cg_brassTime", "2500", CVAR_ARCHIVE )
CG_CVAR( cg_chatTime, "cg_chatTime", "3500", CVAR_ARCHIVE )
CG_CVAR( cg_addMarks, "cg_marks", "1", CVAR_ARCHIVE )
CG_CVAR( cg_railTrailTime, "cg_railTrailTime", "400", CVAR_ARCHIVE  )
CG_CVAR( cg_centertime, "cg_centertime", "3", CVAR_CHEAT )
CG_CVAR( cg_runpitch, "cg_runpitch", "0.002", CVAR_ARCHIVE )
CG_CVAR( cg_runroll, "cg_runroll", "0.005", CVAR_ARCHIVE )
CG_CVAR( cg_bobup , "cg_bobup", "0.005", CVAR_ARCHIVE )
CG_CVAR( cg_bobpitch, "cg_bobpitch", "0.002", CVAR_ARCHIVE )
CG_CVAR( cg_bobroll, "cg_bobroll", "0.002", CVAR_ARCHIVE )
CG_CVAR( cg_swingSpeed, "cg_swingSpeed", "0.3", CVAR_CHEAT )
CG_CVAR( cg_animSpeed, "cg_animspeed", "1", CVAR_CHEAT )
CG_CVAR( cg_debugAnim, "cg_debuganim", "0", CVAR_CHEAT )
CG_CVAR( cg_debugPosition, "cg_debugposition", "0", CVAR_CHEAT )
CG_CVAR( cg_debugEvents, "cg_debugevents", "0", CVAR_CHEAT )
CG_CVAR( cg_errorDecay, "cg_errordecay", "100", 0 )
CG_CVAR( cg_nopredict, "cg_nopredict", "0", 0 )
CG_CVAR( cg_noPlayerAnims, "cg_noplayeranims", "0", CVAR_CHEAT )
CG_CVAR( cg_showmiss, "cg_showmiss", "0", 0 )
CG_CVAR( cg_footsteps, "cg_footsteps", "1", CVAR_CHEAT )
CG_CVAR( cg_tracerChance, "cg_tracerchance", "0.4", CVAR_CHEAT )
CG_CVAR( cg_tracerWidth, "cg_tracerwidth", "1", CVAR_CHEAT )
CG_CVAR( cg_tracerLength, "cg_tracerlength", "100", CVAR_CHEAT )
CG_CVAR( cg_lockedRange, "cg_lockedRange", "30", CVAR_ARCHIVE )
CG_CVAR( cg_lockedAngle, "cg_lockedAngle", "320", 0 )
CG_CVAR( cg_lockedHeight, "cg_lockedHeight", "0", CVAR_ARCHIVE )
CG_CVAR( cg_lockedSlide, "cg_lockedSlide", "40", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonRange, "cg_thirdPersonRange", "80", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonAngle, "cg_thirdPersonAngle", "0", 0 )
CG_CVAR( cg_thirdPersonHeight, "cg_thirdPersonHeight", "0", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonSlide, "cg_thirdPersonSlide", "-20", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonCameraDamp, "cg_thirdPersonCameraDamp", "0.2", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonTargetDamp, "cg_thirdPersonTargetDamp", "0.5", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonMeleeCameraDamp, "cg_thirdPersonMeleeCameraDamp", "0.1", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPersonMeleeTargetDamp, "cg_thirdPersonMeleeTargetDamp", "0.9", CVAR_ARCHIVE )
CG_CVAR( cg_thirdPerson, "cg_thirdPerson", "0", CVAR_ARCHIVE )
CG_CVAR( cg_teamChatTime, "cg_teamChatTime", "3000", CVAR_ARCHIVE  )
CG_CVAR( cg_teamChatHeight, "cg_teamChatHeight", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_forceModel, "cg_forceModel", "0", CVAR_ARCHIVE  )
CG_CVAR( cg_deferPlayers, "cg_deferPlayers", "1", CVAR_ARCHIVE )
CG_CVAR( cg_drawTeamOverlay, "cg_drawTeamOverlay", "0", CVAR_ARCHIVE )
CG_CVAR( cg_teamOverlayUserinfo, "teamoverlay", "0", CVAR_ROM | CVAR_USERINFO )
CG_CVAR( cg_stats, "cg_stats", "0", 0 )
CG_CVAR( cg_drawFriend, "cg_drawFriend", "1", CVAR_ARCHIVE )
CG_CVAR( cg_teamChatsOnly, "cg_teamChatsOnly", "0", CVAR_ARCHIVE )
CG_CVAR( cg_noVoiceChats, "cg_noVoiceChats", "0", CVAR_ARCHIVE )
CG_CVAR( cg_noVoiceText, "cg_noVoiceText", "0", CVAR_ARCHIVE )
CG_CVAR( cg_buildScript, "com_buildScript", "0", 0 )	// force loading of all possible data and error on failures
CG_CVAR( cg_paused, "cl_paused", "0", CVAR_ROM )
CG_CVAR( cg_blood, "com_blood", "1", CVAR_ARCHIVE )
CG_CVAR( cg_synchronousClients, "g_synchronousClients", "1", 0 )	// communicated by systeminfo
CG_CVAR( cg_enableDust, "g_enableDust", "0", CVAR_SERVERINFO )
CG_CVAR( cg_enableBreath, "g_enableBreath", "1", CVAR_SERVERINFO )
CG_CVAR( cg_cameraOrbit, "cg_cameraOrbit", "0", CVAR_ARCHIVE )
CG_CVAR( cg_cameraOrbitDelay, "cg_cameraOrbitDelay", "50", CVAR_ARCHIVE )
CG_CVAR( cg_timescaleFadeEnd, "cg_timescaleFadeEnd", "1", 0 )
CG_CVAR( cg_timescaleFadeSpeed, "cg_timescaleFadeSpeed", "0", 0 )
CG_CVAR( cg_timescale, "timescale", "1", 0 )
CG_CVAR( cg_scorePlum, "cg_scorePlums", "1", CVAR_USERINFO | CVAR_ARCHIVE )
CG_CVAR( cg_smoothClients, "cg_smoothClients", "0", CVAR_USERINFO | CVAR_ARCHIVE )
CG_CVAR( cg_cameraMode, "com_cameraMode", "0", CVAR_CHEAT )

CG_CVAR( pmove_fixed, "pmove_fixed", "0", CVAR_SYSTEMINFO )
CG_CVAR( pmove_msec, "pmove_msec", "8", CVAR_SYSTEMINFO )
CG_CVAR( cg_smallFont, "ui_smallFont", "0.25", CVAR_ARCHIVE )
CG_CVAR( cg_bigFont, "ui_bigFont", "0.4", CVAR_ARCHIVE )
CG_CVAR( cg_trueLightning, "cg_trueLightning", "0.0", CVAR_ARCHIVE )
// ADDING FOR ZEQ2
CG_CVAR( cg_lockonDistance, "cg_lockonDistance", "150", CVAR_CHEAT )
CG_CVAR( cg_tailDetail,	"cg_tailDetail", "50", CVAR_ARCHIVE )
CG_CVAR( cg_verboseParse, "cg_verboseParse", "0", CVAR_ARCHIVE )
CG_CVAR( r_beamDetail,	"r_beamDetail", "2", CVAR_ARCHIVE )
CG_CVAR( cg_soundAttenuation, "cg_soundAttenuation", "0.0001", CVAR_CHEAT )
CG_CVAR( cg_thirdPersonCamera, "cg_thirdPersonCamera", "1", CVAR_ARCHIVE )
CG_CVAR( cg_beamControl, "cg_beamControl", "1", CVAR_ARCHIVE )
CG_CVAR( cg_trailSegments, "cg_trailSegments", "50", CVAR_ARCHIVE )
CG_CVAR( cg_music, "cg_music", "0.6", CVAR_ARCHIVE )
CG_CVAR( cg_playTransformTrackToEnd, "cg_playTransformTrackToEnd", "0", CVAR_ARCHIVE )
CG_CVAR( cg_particlesType, "cg_particlesType", "1", CVAR_ARCHIVE )
CG_CVAR( cg_particlesQuality, "cg_particlesQuality", "1", CVAR_ARCHIVE )
CG_CVAR( cg_particlesStop, "cg_particlesStop", "0", CVAR_ARCHIVE )
CG_CVAR( cg_particlesMaximum, "cg_particlesMaximum", "1024", CVAR_ARCHIVE )
CG_CVAR( cg_drawBBox, "cg_drawBBox", "0", CVAR_CHEAT )
// END ADDING
//CG_CVAR( cg_pmove_fixed, "cg_pmove_fixed", "0", CVAR_USERINFO | CVAR_ARCHIVE )

#undef CG_CVAR
